version: '3'

volumes: 
  datafiles:

services:
   mysql:
     image: mysql:8.0.0
     container_name: home-db
     environment: 
       - MYSQL_ROOT_PASSWORD=lhy_2016
       - MYSQL_TCP_PORT=3306
     volumes: 
       - datafiles:/var/lib/mysql
     restart: always
   home:
     container_name: lhy-home
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       - MYSQL_DBHOST=mysql
       - MYSQL_DBPORT=3306
       - MYSQL_DBUSER=root
       - MYSQL_DBPASS=lhy_2016
       #- MYSQL_DBNAME=
      #ports:
      # - 8080:80
      # - 8083:443
     expose:
       - "80"
     depends_on:
             - mysql
     volumes:
       - ./:/var/www/html/
