version: '3'

services:
   home-db:
     image: mysql:5.7
     container_name: home-db
     environment: 
       - MYSQL_ROOT_PASSWORD=lhy_2016
      #  - MYSQL_TCP_PORT=3306
    #  ports:
    #    - "32001:3306"
     volumes: 
       - ./dbData:/var/lib/mysql
     restart: always
   
   
   home:
     container_name: lhy-home
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       - MYSQL_DBHOST=home-db
       - MYSQL_DBPORT=3306
       - MYSQL_DBUSER=root
       - MYSQL_DBPASS=lhy_2016
       #- MYSQL_DBNAME=
      #ports:
      # - 8080:80
      # - 8083:443
     expose:
       - "80"
     depends_on:
       - home-db
     volumes:
       - ./:/var/www/html/
